const fs=require("fs"),P=require("path");
const {cats:CATS,tools:TOOLS}=require("./src/tools.js");
const SITE=process.env.CF_PAGES_URL||"https://quicktools.pages.dev";
const LANGS=["en","es"];
const UI={tag:{en:"Free online calculators",es:"Calculadoras online gratis"},home:{en:"Home",es:"Inicio"},try:{en:"Try also",es:"Prueba también"},faq:{en:"FAQ",es:"Preguntas frecuentes"},how:{en:"How to use",es:"Cómo usar"},share:{en:"Share",es:"Compartir"},fav:{en:"Save",es:"Guardar"},pop:{en:"Most popular",es:"Más populares"},all:{en:"tools",es:"herramientas"},disc:{en:"Results are informative only.",es:"Resultados solo informativos."},privacy:{en:"Privacy",es:"Privacidad"},terms:{en:"Terms",es:"Términos"},about:{en:"About",es:"Acerca de"},contact:{en:"Contact",es:"Contacto"}};
const POP=["mortgage-loan","bmi","percentage","tip","calories"];
const byId=id=>TOOLS.find(t=>t.id===id);
const W=(f,c)=>{fs.mkdirSync(P.dirname(f),{recursive:true});fs.writeFileSync(f,c)};
const tile=(l,t)=>`<a class="tile" href="/${l}/${t.cat}/${t.id}/">${t[l]}</a>`;
function header(l,path){const alt="/"+(l==="en"?"es":"en")+path.slice(3);return `<header><a class="brand" href="/${l}/">QuickTools</a><nav class="top">${CATS.map(c=>`<a href="/${l}/${c.id}/">${c[l]}</a>`).join("")}</nav><span class="lang"><a href="${alt}">${l==="en"?"ES":"EN"}</a><button id="themeBtn">◐</button></span></header>`}
function footer(l){return `<footer><p>${UI.disc[l]}</p><p><a href="/${l}/about/">${UI.about[l]}</a> · <a href="/${l}/privacy/">${UI.privacy[l]}</a> · <a href="/${l}/terms/">${UI.terms[l]}</a> · <a href="/${l}/contact/">${UI.contact[l]}</a></p></footer>`}
function page(l,path,title,desc,body){const alt=x=>"/"+(x==="en"?"es":"en")+path.slice(3);return `<!DOCTYPE html><html lang="${l}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${desc}"><link rel="canonical" href="${SITE}${path}"><link rel="alternate" hreflang="en" href="${SITE}${alt("en")}"><link rel="alternate" hreflang="es" href="${SITE}${alt("es")}"><link rel="alternate" hreflang="x-default" href="${SITE}${alt("en")}"><link rel="stylesheet" href="/assets/styles.css"></head><body>${header(l,path)}<main>${body}</main>${footer(l)}<script src="/assets/app.js"></script></body></html>`}
function toolBody(l,t){const cat=CATS.find(c=>c.id===t.cat);const rel=[...t.rel.map(byId).filter(Boolean),...TOOLS.filter(x=>x.cat===t.cat&&!t.rel.includes(x.id)&&x.id!==t.id).slice(0,2)];
return `<nav class="crumb"><a href="/${l}/">${UI.home[l]}</a> › <a href="/${l}/${t.cat}/">${cat[l]}</a></nav><h1>${t[l]}</h1><p class="desc">${UI.tag[l]}</p><div class="card"><div id="fields" class="fields"></div><div id="res" class="res"></div><div class="acts"><button id="share">↗ ${UI.share[l]}</button><button id="fav">☆ ${UI.fav[l]}</button></div></div><div class="ad">Ad</div><h2>${UI.how[l]}</h2><ol>${t.f.map(fd=>`<li>${l==="es"?"Ingresa":"Enter"} ${(l==="es"?fd[3]:fd[2]).toLowerCase()}</li>`).join("")}</ol><h2>${UI.faq[l]}</h2>${l==="en"?"<h3>Is it free?</h3><p>Yes. Free, unlimited, no registration.</p><h3>Does it store my data?</h3><p>No. Everything runs in your browser.</p>":"<h3>¿Es gratis?</h3><p>Sí. Gratis, ilimitada y sin registro.</p><h3>¿Guarda mis datos?</h3><p>No. Todo se calcula en tu navegador.</p>"}<h2>${UI.try[l]}</h2><div class="grid">${rel.map(r=>tile(l,r)).join("")}</div><script>window.LANG="${l}";window.TOOL=${JSON.stringify({f:t.f,calc:t.calc})};</script>`}
function hubBody(l,c){const list=TOOLS.filter(t=>t.cat===c.id);return `<nav class="crumb"><a href="/${l}/">${UI.home[l]}</a></nav><h1>${c[l]}</h1><p class="desc">${UI.tag[l]}</p><div class="grid">${list.map(t=>tile(l,t)).join("")}</div><h2>${UI.try[l]}</h2><div class="grid">${CATS.filter(x=>x.id!==c.id).map(x=>`<a class="tile" href="/${l}/${x.id}/">${x[l]}</a>`).join("")}</div>`}
function homeBody(l){return `<h1>${l==="es"?"Calculadoras online gratis":"Free online calculators"}</h1><p class="desc">${UI.tag[l]}</p><input id="q" class="q" placeholder="${l==="es"?"Buscar…":"Search…"}"><div class="grid">${CATS.map(c=>`<a class="tile" href="/${l}/${c.id}/"><b>${c[l]}</b><br>${TOOLS.filter(t=>t.cat===c.id).length} ${UI.all[l]}</a>`).join("")}</div><h2>${UI.pop[l]}</h2><div class="grid">${POP.map(id=>tile(l,byId(id))).join("")}</div>`}
const legal=(l,t,b)=>`<h1>${t}</h1>${b}`;
const paths=[];
LANGS.forEach(l=>{
 paths.push("/"+l+"/");W("dist/"+l+"/index.html",page(l,"/"+l+"/","QuickTools – "+UI.tag[l],UI.tag[l],homeBody(l)));
 CATS.forEach(c=>{const p="/"+l+"/"+c.id+"/";paths.push(p);W("dist"+p+"index.html",page(l,p,c[l]+" – QuickTools",UI.tag[l],hubBody(l,c)))});
 TOOLS.forEach(t=>{const p="/"+l+"/"+t.cat+"/"+t.id+"/";paths.push(p);W("dist"+p+"index.html",page(l,p,t[l]+" – QuickTools",t[l]+". "+UI.tag[l],toolBody(l,t)))});
 [["about",legal(l,UI.about[l],"<p>QuickTools. "+UI.tag[l]+".</p>")],["privacy",legal(l,UI.privacy[l],"<p>"+(l==="es"?"No guardamos datos personales. Los cálculos ocurren en tu navegador. Usamos cookies solo para idioma y tema.":"We do not store personal data. Calculations run in your browser. Cookies are used only for language and theme.")+"</p>")],["terms",legal(l,UI.terms[l],"<p>"+UI.disc[l]+"</p>")],["contact",legal(l,UI.contact[l],"<p>contact@quicktools.site</p>")]].forEach(x=>{const p="/"+l+"/"+x[0]+"/";paths.push(p);W("dist"+p+"index.html",page(l,p,x[1],"QuickTools",x[2]))});
});
W("dist/index.html",'<!DOCTYPE html><meta charset="utf-8"><script>location.replace((navigator.language||"en").indexOf("es")===0?"/es/":"/en/")</script>');
W("dist/sitemap.xml",'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.s
