module.exports={cats:[
{id:"money",en:"Money",es:"Finanzas"},
{id:"health",en:"Health",es:"Salud"},
{id:"everyday",en:"Everyday",es:"Utilidades"},
{id:"fun",en:"Fun",es:"Divertidas"}],
tools:[
{id:"mortgage-loan",cat:"money",rel:["compound-interest","credit-card-payoff","retirement"],en:"Mortgage / Loan Calculator",es:"Calculadora de Préstamo / Hipoteca",
f:[["amount","n","Loan amount","Monto del préstamo",200000],["rate","n","Annual rate (%)","Tasa anual (%)",6.5],["years","n","Years","Años",30]],
calc:`v=>{const r=v.rate/100/12,n=v.years*12;const p=r?v.amount*r/(1-Math.pow(1+r,-n)):v.amount/n;return[["Monthly payment","Cuota mensual",M(p)],["Total paid","Total pagado",M(p*n)],["Total interest","Interés total",M(p*n-v.amount)]]}`},
{id:"compound-interest",cat:"money",rel:["mortgage-loan","retirement","credit-card-payoff"],en:"Compound Interest Calculator",es:"Calculadora de Interés Compuesto",
f:[["principal","n","Initial amount","Monto inicial",1000],["monthly","n","Monthly contribution","Aporte mensual",100],["rate","n","Annual rate (%)","Tasa anual (%)",8],["years","n","Years","Años",10]],
calc:`v=>{const r=v.rate/100/12,n=v.years*12;const t=v.principal*Math.pow(1+r,n)+(r?v.monthly*(Math.pow(1+r,n)-1)/r:v.monthly*n);const c=v.principal+v.monthly*n;return[["Final total","Total final",M(t)],["Contributed","Aportado",M(c)],["Interest","Intereses",M(t-c)]]}`},
{id:"credit-card-payoff",cat:"money",rel:["mortgage-loan","compound-interest","tip"],en:"Credit Card Payoff Calculator",es:"Calculadora de Pago de Tarjeta de Crédito",
f:[["balance","n","Balance","Saldo",5000],["apr","n","APR (%)","Tasa anual (%)",24],["pay","n","Monthly payment","Pago mensual",150]],
calc:`v=>{const i=v.apr/100/12;if(v.pay<=v.balance*i)return[["Result","Resultado",L==="es"?"Nunca se pagará: sube el pago":"Never pays off: increase payment"]];const m=Math.ceil(-Math.log(1-v.balance*i/v.pay)/Math.log(1+i));return[["Months to payoff","Meses para pagar",N(m)],["Years","Años",N(m/12,1)],["Total interest","Interés total",M(v.pay*m-v.balance)]]}`},
{id:"hourly-to-salary",cat:"money",rel:["retirement","margin2","compound-interest"],en:"Hourly to Salary Calculator",es:"Calculadora de Salario por Hora",
f:[["hourly","n","Hourly rate","Tarifa por hora",25],["hpw","n","Hours per week","Horas por semana",40]],
calc:`v=>{const a=v.hourly*v.hpw*52;return[["Annual","Anual",M(a)],["Monthly","Mensual",M(a/12)],["Weekly","Semanal",M(a/52)]]}`},
{id:"retirement",cat:"money",rel:["compound-interest","mortgage-loan","hourly-to-salary"],en:"Retirement Savings Calculator",es:"Calculadora de Ahorro para Jubilación",
f:[["cur","n","Current savings","Ahorro actual",10000],["m","n","Monthly saving","Ahorro mensual",300],["r","n","Annual return (%)","Rendimiento anual (%)",7],["y","n","Years","Años",25]],
calc:`v=>{const r=v.r/100/12,n=v.y*12;const t=v.cur*Math.pow(1+r,n)+(r?v.m*(Math.pow(1+r,n)-1)/r:v.m*n);return[["At retirement","Al jubilarte",M(t)],["Contributed","Aportado",M(v.cur+v.m*n)]]}`},
{id:"bmi",cat:"health",rel:["calories","water","ideal-weight"],en:"BMI Calculator",es:"Calculadora de IMC",
f:[["w","n","Weight (kg)","Peso (kg)",70],["h","n","Height (cm)","Altura (cm)",170]],
calc:`v=>{const b=v.w/Math.pow(v.h/100,2);const c=b<18.5?(L==="es"?"Bajo peso":"Underweight"):b<25?(L==="es"?"Peso normal":"Normal weight"):b<30?(L==="es"?"Sobrepeso":"Overweight"):(L==="es"?"Obesidad":"Obesity");return[["BMI","IMC",N(b,1)],["Category","Categoría",c]]}`},
{id:"calories",cat:"health",rel:["bmi","water","tip"],en:"Calorie Calculator (TDEE)",es:"Calculadora de Calorías (TDEE)",
f:[["sex","s","Sex","Sexo",[["m","Male","Hombre"],["f","Female","Mujer"]],"m"],["age","n","Age","Edad",30],["w","n","Weight (kg)","Peso (kg)",70],["h","n","Height (cm)","Altura (cm)",170],["act","s","Activity","Actividad",[["1.2","Sedentary","Sedentario"],["1.375","Light","Ligero"],["1.55","Moderate","Moderado"],["1.725","High","Alto"]],"1.375"]],
calc:`v=>{const b=10*v.w+6.25*v.h-5*v.age+(v.sex==="m"?5:-161);const t=b*v.act;return[["Maintenance","Mantención",N(t)+" cal"],["Mild weight loss","Pérdida ligera",N(t*0.85)+" cal"],["BMR","TMB",N(b)+" cal"]]}`},
{id:"water",cat:"health",rel:["bmi","calories","age"],en:"Water Intake Calculator",es:"Calculadora de Agua Diaria",
f:[["w","n","Weight (kg)","Peso (kg)",70],["act","s","Exercise per week","Ejercicio por semana",[["0","0-1 days","0-1 días"],["1","2-3 days","2-3 días"],["2","4+ days","4+ días"]],"1"]],
calc:`v=>{const l=v.w*0.033+Number(v.act)*0.5;return[["Water per day","Agua por día",N(l,1)+" L"]]}`},
{id:"ideal-weight",cat:"health",rel:["bmi","calories","sleep-cycles"],en:"Ideal Weight Calculator",es:"Calculadora de Peso Ideal",
f:[["sex","s","Sex","Sexo",[["m","Male","Hombre"],["f","Female","Mujer"]],"m"],["h","n","Height (cm)","Altura (cm)",170]],
calc:`v=>{const b=(v.sex==="m"?50:45.5)+0.9*(v.h-152);return[["Ideal weight","Peso ideal",N(b,1)+" kg"],["Healthy range","Rango saludable",N(b*0.9,0)+"–"+N(b*1.1,0)+" kg"]]}`},
{id:"sleep-cycles",cat:"health",rel:["calories","bmi","age"],en:"Sleep Cycle Calculator",es:"Calculadora de Ciclos de Sueño",
f:[["wake","t","Wake-up time","Hora de despertar","07:00"]],
calc:`v=>{const p=v.wake.split(":");const w=(+p[0])*60+(+p[1]||0);const f=function(c){let m=w-(c*90+15);m=((m%1440)+1440)%1440;const h=Math.floor(m/60),mm=m%60;return(h<10?"0":"")+h+":"+(mm<10?"0":"")+mm};return[["6 cycles (9h)","6 ciclos (9h)",f(6)],["5 cycles (7.5h)","5 ciclos (7.5h)",f(5)],["4 cycles (6h)","4 ciclos (6h)",f(4)]]}`},
{id:"percentage",cat:"everyday",rel:["discount","tip","date-difference"],en:"Percentage Calculator",es:"Calculadora de Porcentaje",
f:[["p","n","Percent (%)","Porcentaje (%)",15],["x","n","Of value","Del valor",200]],
calc:`v=>{const a=v.p/100*v.x;return[[v.p+"% of "+v.x,v.p+"% de "+v.x,M(a)],["X + P%","X + P%",M(v.x+a)],["X - P%","X - P%",M(v.x-a)]]}`},
{id:"age",cat:"everyday",rel:["date-diff2","bmi","percentage"],en:"Age Calculator",es:"Calculadora de Edad",
f:[["dob","d","Date of birth","Fecha de nacimiento","2000-01-01"]],
calc:`v=>{const b=new Date(v.dob),n=new Date();let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),d=n.getDate()-b.getDate();if(d<0){m--;d+=30}if(m<0){y--;m+=12}const days=Math.floor((n-b)/864e5);return[["Age","Edad",y+" "+(L==="es"?"años, ":"yrs, ")+m+" "+(L==="es"?"meses":"mo")],["Total days","Días totales",N(days)]]}`},
{id:"tip",cat:"everyday",rel:["discount","percentage","calories"],en:"Tip Calculator",es:"Calculadora de Propinas",
f:[["bill","n","Bill","Cuenta",50],["tip","s","Tip %","Propina %",[["10","10%","10%"],["15","15%","15%"],["18","18%","18%"],["20","20%","20%"],["25","25%","25%"]],"15"],["split","n","People","Personas",2]],
calc:`v=>{const t=v.bill*v.tip/100,tot=v.bill+t;return[["Tip","Propina",M(t)],["Total","Total",M(tot)],["Per person","Por persona",M(tot/v.split)]]}`},
{id:"discount",cat:"everyday",rel:["percentage","tip","mortgage-loan"],en:"Discount Calculator",es:"Calculadora de Descuento",
f:[["price","n","Price","Precio",100],["off","n","Discount (%)","Descuento (%)",20]],
calc:`v=>{const s=v.price*v.off/100;return[["Final price","Precio final",M(v.price-s)],["You save","Ahorras",M(s)]]}`},
{id:"date-difference",cat:"everyday",rel:["age","percentage","tip"],en:"Date Difference Calculator",es:"Calculadora de Días Entre Fechas",
f:[["a","d","Start","Inicio","2025-01-01"],["b","d","End","Fin","2025-12-31"]],
calc:`v=>{const d=Math.abs((new Date(v.b)-new Date(v.a))/864e5);return[["Days","Días",N(d)],["Weeks","Semanas",N(d/7,1)],["Months","Meses",N(d/30.44,1)]]}`},
{id:"chaos-level",cat:"fun",rel:["mental-age","compatibility","tip"],en:"Chaos Level Calculator",es:"Calculadora de Nivel de Caos",
f:[["q1","r","You replied 'k' and moved on","Respondiste 'k' y seguiste con tu vida",1],["q2","r","30+ tabs open","30+ pestañas abiertas",1],["q3","r","'On my way' from bed","'Voy en camino' desde la cama",1],["q4","r","Alarm with 5+ snoozes","Alarma con 5+ posponer",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const p=Math.round((s-4)/16*100);const m=p<34?(L==="es"?"Caos ligero. Casi funcional.":"Light chaos. Almost functional."):p<67?(L==="es"?"Caos medio. Profesional del 'luego lo hago'.":"Medium chaos. Professional 'later'."):(L==="es"?"Caos legendario.":"Legendary chaos.");return[["Chaos level","Nivel de caos",p+"%"],["Result","Resultado",m]]}`},
{id:"mental-age",cat:"fun",rel:["chaos-level","compatibility","age"],en:"Mental Age Calculator",es:"Calculadora de Edad Mental",
f:[["q1","r","You still watch cartoons","Sigues viendo dibujos animados",1],["q2","r","Champion napper","Siesta como campeón",1],["q3","r","Google instead of remembering","Googles en vez de recordar",1],["q4","r","2 AM purchases","Compras a las 2 AM",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const a=Math.round(8+(s-4)/16*72);return[["Mental age","Edad mental",a+" "+(L==="es"?"años":"yrs")],["Result","Resultado",a<20?(L==="es"?"Energía juvenil infinita.":"Endless youthful energy."):a<50?(L==="es"?"Equilibrio sospechoso.":"Suspicious balance."):(L==="es"?"Sabiduría de abuelo.":"Grandpa wisdom.")]]}`},
{id:"compatibility",cat:"fun",rel:["chaos-level","mental-age","percentage"],en:"Compatibility Calculator",es:"Calculadora de Compatibilidad",
f:[["a","t","First name","Primer nombre","Ana"],["b","t","Second name","Segundo nombre","Luis"]],
calc:`v=>{const s=(v.a+"|"+v.b).toLowerCase().replace(/\\s/g,"");let h=7;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))%101;return[["Compatibility","Compatibilidad",h+"%"],["Result","Resultado",h>70?(L==="es"?"Dúo poderoso.":"Power duo."):h>40?(L==="es"?"Equipo posible con café.":"Possible team with coffee."):(L==="es"?"Mejor separados.":"Better separately.")]]}`},
{id:"dog-years",cat:"fun",rel:["age","chaos-level","mental-age"],en:"Dog Years Calculator",es:"Calculadora de Años Perrunos",
f:[["age","n","Dog age","Edad del perro",3],["size","s","Size","Tamaño",[["s","Small","Pequeño"],["m","Medium","Mediano"],["l","Large","Grande"]],"m"]],
calc:`v=>{const k=v.size==="s"?4:v.size==="m"?5:6;const h=v.age<=1?15*v.age:v.age<=2?15+(v.age-1)*9:24+(v.age-2)*k;return[["Human years","Años humanos",N(h,0)],["Stage","Etapa",h<15?(L==="es"?"Joven":"Young"):h<60?(L==="es"?"Adulto":"Adult"):(L==="es"?"Senior":"Senior")]]}`},
{id:"procrastination",cat:"fun",rel:["chaos-level","mental-age","date-difference"],en:"Procrastination Calculator",es:"Calculadora de Procrastinación",
f:[["q1","r","Left things for 'tomorrow'","Dejaste cosas para 'mañana'",1],["q2","r","Unfinished series","Series sin terminar",1],["q3","r","Cleaned instead of working","Limpiaste en vez de trabajar",1],["q4","r","Started 5 projects, finished 0","5 proyectos, 0 terminados",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const p=Math.round((s-4)/16*100);return[["Procrastination","Procrastinación",p+"%"],["Result","Resultado",p<34?(L==="es"?"Productivo sospechoso.":"Suspiciously productive."):p<67?(L==="es"?"Mañana empieza… de nuevo.":"Starts tomorrow… again."):(L==="es"?"El 'luego' es tu estilo de vida.":"'Later' is your lifestyle.")]]}`}
]};
