module.exports={cats:[
{id:"money",en:"Money",es:"Finanzas",intro:{en:"Calculators for loans, mortgages, compound interest, credit cards and retirement. Instant, free results.",es:"Calculadoras de préstamos, hipotecas, interés compuesto, tarjetas de crédito y jubilación. Resultados al instante y gratis."}},
{id:"health",en:"Health",es:"Salud",intro:{en:"BMI, calories, water, ideal weight and sleep cycles. Free health calculators with clear results.",es:"IMC, calorías, agua, peso ideal y ciclos de sueño. Calculadoras de salud gratis con resultados claros."}},
{id:"everyday",en:"Everyday",es:"Utilidades",intro:{en:"Everyday tools: percentage, age, tips, discounts and date differences. Fast and free.",es:"Herramientas diarias: porcentaje, edad, propinas, descuentos y días entre fechas. Rápidas y gratis."}},
{id:"fun",en:"Fun",es:"Divertidas",intro:{en:"Fun tests to share with friends: chaos level, mental age, compatibility and more.",es:"Tests divertidos para compartir con amigos: nivel de caos, edad mental, compatibilidad y más."}}],
tools:[
{id:"mortgage-loan",cat:"money",rel:["compound-interest","credit-card-payoff","retirement"],en:"Mortgage / Loan",es:"Préstamo / Hipoteca",d:{en:"Monthly payment and total interest of your loan",es:"Cuota mensual e interés total de tu préstamo"},
f:[["amount","n","Amount","Monto",200000],["rate","n","Rate (%)","Tasa (%)",6.5],["years","n","Years","Años",30]],
calc:`v=>{const r=v.rate/100/12,n=v.years*12;const p=r?v.amount*r/(1-Math.pow(1+r,-n)):v.amount/n;return[["Monthly","Mensual",M(p)],["Total","Total",M(p*n)],["Interest","Interés",M(p*n-v.amount)]]}`},
{id:"compound-interest",cat:"money",rel:["mortgage-loan","retirement","credit-card-payoff"],en:"Compound Interest",es:"Interés Compuesto",d:{en:"See how your money grows over time",es:"Mira cómo crece tu dinero con el tiempo"},
f:[["principal","n","Initial","Inicial",1000],["monthly","n","Monthly","Mensual",100],["rate","n","Rate (%)","Tasa (%)",8],["years","n","Years","Años",10]],
calc:`v=>{const r=v.rate/100/12,n=v.years*12;const t=v.principal*Math.pow(1+r,n)+(r?v.monthly*(Math.pow(1+r,n)-1)/r:v.monthly*n);const c=v.principal+v.monthly*n;return[["Final","Final",M(t)],["Contributed","Aportado",M(c)],["Interest","Intereses",M(t-c)]]}`},
{id:"credit-card-payoff",cat:"money",rel:["mortgage-loan","compound-interest","tip"],en:"Credit Card Payoff",es:"Pago de Tarjeta",d:{en:"How many months to pay off your balance",es:"En cuántos meses pagarás tu saldo"},
f:[["balance","n","Balance","Saldo",5000],["apr","n","APR (%)","Tasa (%)",24],["pay","n","Monthly Pay","Pago mensual",150]],
calc:`v=>{const i=v.apr/100/12;if(v.pay<=v.balance*i)return[["Result","Resultado",L==="es"?"Aumenta el pago":"Increase payment"]];const m=Math.ceil(-Math.log(1-v.balance*i/v.pay)/Math.log(1+i));return[["Months","Meses",N(m)],["Years","Años",N(m/12,1)],["Interest","Interés",M(v.pay*m-v.balance)]]}`},
{id:"hourly-to-salary",cat:"money",rel:["retirement","compound-interest","tip"],en:"Hourly to Salary",es:"Salario por Hora",d:{en:"Convert your hourly rate to annual salary",es:"Convierte tu tarifa por hora en sueldo anual"},
f:[["hourly","n","Hourly","Por hora",25],["hpw","n","Hours/week","Horas/sem",40]],
calc:`v=>{const a=v.hourly*v.hpw*52;return[["Annual","Anual",M(a)],["Monthly","Mensual",M(a/12)],["Weekly","Semanal",M(a/52)]]}`},
{id:"retirement",cat:"money",rel:["compound-interest","mortgage-loan","hourly-to-salary"],en:"Retirement Savings",es:"Jubilación",d:{en:"How much you'll have when you retire",es:"Cuánto tendrás al jubilarte"},
f:[["cur","n","Current","Actual",10000],["m","n","Monthly","Mensual",300],["r","n","Return (%)","Rend. (%)",7],["y","n","Years","Años",25]],
calc:`v=>{const r=v.r/100/12,n=v.y*12;const t=v.cur*Math.pow(1+r,n)+(r?v.m*(Math.pow(1+r,n)-1)/r:v.m*n);return[["Final","Final",M(t)],["Contributed","Aportado",M(v.cur+v.m*n)]]}`},
{id:"bmi",cat:"health",rel:["calories","water","ideal-weight"],en:"BMI Calculator",es:"Calculadora IMC",d:{en:"Body mass index with category",es:"Índice de masa corporal con categoría"},
f:[["w","n","Weight (kg)","Peso (kg)",70],["h","n","Height (cm)","Altura (cm)",170]],
calc:`v=>{const b=v.w/Math.pow(v.h/100,2);const c=b<18.5?(L==="es"?"Bajo peso":"Underweight"):b<25?(L==="es"?"Normal":"Normal"):b<30?(L==="es"?"Sobrepeso":"Overweight"):(L==="es"?"Obesidad":"Obesity");return[["BMI","IMC",N(b,1)],["Category","Categoría",c]]}`},
{id:"calories",cat:"health",rel:["bmi","water","tip"],en:"Calories (TDEE)",es:"Calorías (TDEE)",d:{en:"Daily calories for your goal",es:"Calorías diarias según tu objetivo"},
f:[["sex","s","Sex","Sexo",[["m","Male","Hombre"],["f","Female","Mujer"]],"m"],["age","n","Age","Edad",30],["w","n","Weight (kg)","Peso (kg)",70],["h","n","Height (cm)","Altura (cm)",170],["act","s","Activity","Actividad",[["1.2","Sedentary","Sedentario"],["1.375","Light","Ligero"],["1.55","Moderate","Moderado"],["1.725","High","Alto"]],"1.375"]],
calc:`v=>{const b=10*v.w+6.25*v.h-5*v.age+(v.sex==="m"?5:-161);const t=b*v.act;return[["Maintenance","Mantención",N(t)+" cal"],["Weight loss","Pérdida",N(t*0.85)+" cal"],["BMR","TMB",N(b)+" cal"]]}`},
{id:"water",cat:"health",rel:["bmi","calories","age"],en:"Water Intake",es:"Agua Diaria",d:{en:"How much water you should drink",es:"Cuánta agua debes tomar al día"},
f:[["w","n","Weight (kg)","Peso (kg)",70],["act","s","Exercise","Ejercicio",[["0","0-1 days","0-1 días"],["1","2-3 days","2-3 días"],["2","4+ days","4+ días"]],"1"]],
calc:`v=>{const l=v.w*0.033+Number(v.act)*0.5;return[["Water","Agua",N(l,1)+" L"]]}`},
{id:"ideal-weight",cat:"health",rel:["bmi","calories","sleep-cycles"],en:"Ideal Weight",es:"Peso Ideal",d:{en:"Healthy weight range for your height",es:"Rango de peso saludable para tu altura"},
f:[["sex","s","Sex","Sexo",[["m","Male","Hombre"],["f","Female","Mujer"]],"m"],["h","n","Height (cm)","Altura (cm)",170]],
calc:`v=>{const b=(v.sex==="m"?50:45.5)+0.9*(v.h-152);return[["Ideal","Ideal",N(b,1)+" kg"],["Range","Rango",N(b*0.9,0)+"–"+N(b*1.1,0)+" kg"]]}`},
{id:"sleep-cycles",cat:"health",rel:["calories","bmi","age"],en:"Sleep Cycles",es:"Ciclos de Sueño",d:{en:"Best bedtimes to wake up fresh",es:"Mejores horas para dormir y despertar bien"},
f:[["wake","t","Wake-up","Despertar","07:00"]],
calc:`v=>{const p=v.wake.split(":");const w=(+p[0])*60+(+p[1]||0);const f=function(c){let m=w-(c*90+15);m=((m%1440)+1440)%1440;const h=Math.floor(m/60),mm=m%60;return(h<10?"0":"")+h+":"+(mm<10?"0":"")+mm};return[["6 cycles (9h)","6 ciclos (9h)",f(6)],["5 cycles (7.5h)","5 ciclos (7.5h)",f(5)],["4 cycles (6h)","4 ciclos (6h)",f(4)]]}`},
{id:"percentage",cat:"everyday",rel:["discount","tip","date-difference"],en:"Percentage",es:"Porcentaje",d:{en:"Any percentage in one second",es:"Cualquier porcentaje en un segundo"},
f:[["p","n","Percent (%)","Porcentaje (%)",15],["x","n","Value","Valor",200]],
calc:`v=>{const a=v.p/100*v.x;return[[v.p+"% of "+v.x,v.p+"% de "+v.x,M(a)],["X + P%","X + P%",M(v.x+a)],["X - P%","X - P%",M(v.x-a)]]}`},
{id:"age",cat:"everyday",rel:["date-difference","bmi","percentage"],en:"Age Calculator",es:"Calculadora Edad",d:{en:"Exact age in years, months and days",es:"Edad exacta en años, meses y días"},
f:[["dob","d","Birthdate","Nacimiento","2000-01-01"]],
calc:`v=>{const b=new Date(v.dob),n=new Date();let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),d=n.getDate()-b.getDate();if(d<0){m--;d+=30}if(m<0){y--;m+=12}const days=Math.floor((n-b)/864e5);return[["Age","Edad",y+" "+(L==="es"?"años, ":"yrs, ")+m+" "+(L==="es"?"meses":"mo")],["Days","Días",N(days)]]}`},
{id:"tip",cat:"everyday",rel:["discount","percentage","calories"],en:"Tip Calculator",es:"Propinas",d:{en:"Tip and total, split per person",es:"Propina y total, dividido por persona"},
f:[["bill","n","Bill","Cuenta",50],["tip","s","Tip %","Propina %",[["10","10%","10%"],["15","15%","15%"],["18","18%","18%"],["20","20%","20%"],["25","25%","25%"]],"15"],["split","n","People","Personas",2]],
calc:`v=>{const t=v.bill*v.tip/100,tot=v.bill+t;return[["Tip","Propina",M(t)],["Total","Total",M(tot)],["Per person","Por persona",M(tot/v.split)]]}`},
{id:"discount",cat:"everyday",rel:["percentage","tip","mortgage-loan"],en:"Discount",es:"Descuento",d:{en:"Final price and how much you save",es:"Precio final y cuánto ahorras"},
f:[["price","n","Price","Precio",100],["off","n","Discount (%)","Descuento (%)",20]],
calc:`v=>{const s=v.price*v.off/100;return[["Final","Final",M(v.price-s)],["Saved","Ahorras",M(s)]]}`},
{id:"date-difference",cat:"everyday",rel:["age","percentage","tip"],en:"Date Difference",es:"Días entre Fechas",d:{en:"Days, weeks and months between dates",es:"Días, semanas y meses entre fechas"},
f:[["a","d","Start","Inicio","2025-01-01"],["b","d","End","Fin","2025-12-31"]],
calc:`v=>{const d=Math.abs((new Date(v.b)-new Date(v.a))/864e5);return[["Days","Días",N(d)],["Weeks","Semanas",N(d/7,1)],["Months","Meses",N(d/30.44,1)]]}`},
{id:"chaos-level",cat:"fun",rel:["mental-age","compatibility","tip"],en:"Chaos Level",es:"Nivel de Caos",d:{en:"How chaotic is your life?",es:"¿Qué tan caótica es tu vida?"},
f:[["q1","r","Replied 'k'","Respondiste 'k'",1],["q2","r","30+ tabs open","30+ pestañas",1],["q3","r","'On my way' in bed","'Voy' en cama",1],["q4","r","5+ snoozes","5+ posponer",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const p=Math.round((s-4)/16*100);const m=p<34?(L==="es"?"Caos ligero.":"Light chaos."):p<67?(L==="es"?"Caos medio.":"Medium chaos."):(L==="es"?"Caos legendario.":"Legendary chaos.");return[["Level","Nivel",p+"%"],["Result","Resultado",m]]}`},
{id:"mental-age",cat:"fun",rel:["chaos-level","compatibility","age"],en:"Mental Age",es:"Edad Mental",d:{en:"Your true mental age",es:"Tu verdadera edad mental"},
f:[["q1","r","Watch cartoons","Ves dibujos",1],["q2","r","Champion napper","Siestas",1],["q3","r","Google to remember","Googles",1],["q4","r","2 AM purchases","Compras 2 AM",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const a=Math.round(8+(s-4)/16*72);return[["Age","Edad",a+" "+(L==="es"?"años":"yrs")],["Result","Resultado",a<20?(L==="es"?"Energía juvenil.":"Youthful."):a<50?(L==="es"?"Equilibrio.":"Balance."):(L==="es"?"Sabiduría.":"Wisdom.")]]}`},
{id:"compatibility",cat:"fun",rel:["chaos-level","mental-age","percentage"],en:"Compatibility",es:"Compatibilidad",d:{en:"Match two names and see the result",es:"Combina dos nombres y mira el resultado"},
f:[["a","t","Name 1","Nombre 1","Ana"],["b","t","Name 2","Nombre 2","Luis"]],
calc:`v=>{const s=(v.a+"|"+v.b).toLowerCase().replace(/\\s/g,"");let h=7;for(let i=0;i<s.length;i++)h=(h*31+s.charCodeAt(i))%101;return[["Match","Match",h+"%"],["Result","Resultado",h>70?(L==="es"?"Dúo poderoso.":"Power duo."):h>40?(L==="es"?"Con café funciona.":"Needs coffee."):(L==="es"?"Mejor separados.":"Better apart.")]]}`},
{id:"dog-years",cat:"fun",rel:["age","chaos-level","mental-age"],en:"Dog Years",es:"Años Perrunos",d:{en:"Your dog's age in human years",es:"La edad de tu perro en años humanos"},
f:[["age","n","Dog age","Edad perro",3],["size","s","Size","Tamaño",[["s","Small","Pequeño"],["m","Medium","Mediano"],["l","Large","Grande"]],"m"]],
calc:`v=>{const k=v.size==="s"?4:v.size==="m"?5:6;const h=v.age<=1?15*v.age:v.age<=2?15+(v.age-1)*9:24+(v.age-2)*k;return[["Human","Humano",N(h,0)],["Stage","Etapa",h<15?(L==="es"?"Joven":"Young"):h<60?(L==="es"?"Adulto":"Adult"):(L==="es"?"Senior":"Senior")]]}`},
{id:"procrastination",cat:"fun",rel:["chaos-level","mental-age","date-difference"],en:"Procrastination",es:"Procrastinación",d:{en:"How much do you leave for tomorrow?",es:"¿Cuánto dejas para mañana?"},
f:[["q1","r","Left for tomorrow","Dejaste para mañana",1],["q2","r","Unfinished series","Series sin fin",1],["q3","r","Cleaned instead","Limpiaste",1],["q4","r","5 projects, 0 done","5 proyectos, 0 fin",1]],
calc:`v=>{const s=+v.q1+ +v.q2+ +v.q3+ +v.q4;const p=Math.round((s-4)/16*100);return[["Level","Nivel",p+"%"],["Result","Resultado",p<34?(L==="es"?"Productivo.":"Productive."):p<67?(L==="es"?"Mañana empieza.":"Starts tomorrow."):(L==="es"?"El 'luego' es vida.":"'Later' is life.")]]}`}
]};
